from .client import ClientBase
from .commande import CommandeBase
from .commune import CommuneBase
from .conditionnement import ConditionnementBase
from .departement import DepartementBase
from .objet import ObjetBase
from .role import RoleBase
from .roleutilisateur import RoleUtilisateurBase
from .utilisateur import UtilisateurBase